packaging_format = 2

id = "homarr"
name = "Homarr"
description.en = "Customizable browser's home page to interact with your homeserver's Docker containers"
description.fr = "Page d'accueil personnalisable pour interagir avec les conteneurs Docker de votre serveur"

version = "0.13.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://homarr.dev/"
demo = "https://homarr.ajnart.fr/fr"
admindoc = "https://homarr.dev/docs/about"
userdoc = "https://homarr.dev/docs/about"
code = "https://github.com/ajnart/homarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/ajnart/homarr/archive/refs/tags/v0.13.2.tar.gz"
        sha256 = "cf2cb349ae309bc0fe7ea5326ed71e4c182fb3781d56d99595707a247988576f"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = ""
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
